name: Publish NuGet

on:
  push:
    branches:
      - main
    
jobs:
  build:
    name: Update package
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
      
    - name: Restore
      run: |
          dotnet restore Swftx.Wpf/Swftx.Wpf.csproj
          dotnet restore Tests/Swftx.Wpf.Tests/WPF.Styles.Tests.csproj
      
    - name: Building
      run: |
        dotnet build Swftx.Wpf/Swftx.Wpf.csproj -c Release --nologo
        dotnet build Tests/Swftx.Wpf.Tests/Swftx.Wpf.Tests.csproj -c Release --nologo
      
    - name: Testing
      run: dotnet test Tests/Swftx.Wpf.Tests/Swftx.Wpf.Tests.csproj --nologo

    - name: Packing
      run: dotnet pack Swftx.Wpf/Swftx.Wpf.csproj --no-build -c Release -v q

    - name: Publishing
      run: dotnet nuget push "**/*.nupkg" --skip-duplicate -k ${{ secrets.NuGetApiKey }} -s https://api.nuget.org/v3/index.json
