name: Testing

on: [push, pull_request]

jobs:
  test:
    name: Testing
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: |
        dotnet build Swftx.Wpf/Swftx.Wpf.csproj -c Debug --no-restore
        dotnet build Tests/Swftx.Wpf.Tests/Swftx.Wpf.csproj -c Debug --no-restore
      
    - name: Test
      run: dotnet test Tests/Swftx.Wpf.Tests/Swftx.Wpf.csproj --no-build --verbosity normal
